### ISSUE TITLE
Add centre-of-mass function to package? 

### ISSUE THREAD

**Issue by edwardlavender** [kyoustat/Riemann#1]
This is a great package! This is a feature request - if it fits within the scope of the package - it it possible to add a function to calculate the centre of mass of a set of longitude/latitudinal coordinates (with associated weights)? I think this would complement the existing `riem.mean()` and `riem.median()` functions that are based on minimising the geodesic distances between points. Thanks for sharing this resource!

**Comment by kisungyou** [comment]
It sounds a good idea to have this functionality but I think it's not suitable to implement this within `Riemann` package since I would like to focus more on providing a generic set of methodologies for manifold-valued data. You can still write your own function for your use though. Let me know how you think.

**Comment by edwardlavender** [comment]
That makes sense. Thank you for the response!
